// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261008221045_AddFuelNews")]
    partial class AddFuelNews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DoeFuelPrice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("CityKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city_key");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at_utc");

                    b.Property<string>("FuelGrade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("fuel_grade");

                    b.Property<decimal>("MaxPricePerLiter")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("max_price_per_liter");

                    b.Property<decimal>("MinPricePerLiter")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("min_price_per_liter");

                    b.Property<string>("OilCompany")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("oil_company");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("province");

                    b.Property<string>("ProvinceKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("province_key");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("region");

                    b.Property<long?>("ReportId")
                        .HasColumnType("bigint")
                        .HasColumnName("report_id");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source_url");

                    b.Property<DateOnly>("WeekEnd")
                        .HasColumnType("date")
                        .HasColumnName("week_end");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date")
                        .HasColumnName("week_start");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.HasIndex("CityKey", "ProvinceKey", "WeekEnd");

                    b.HasIndex("WeekStart", "CityKey", "ProvinceKey", "OilCompany", "FuelGrade")
                        .IsUnique();

                    b.ToTable("doe_fuel_price", (string)null);
                });

            modelBuilder.Entity("DoeImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("ActiveSlot")
                        .HasColumnType("integer")
                        .HasColumnName("active_slot");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details_json");

                    b.Property<string>("Error")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("error");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at_utc");

                    b.Property<DateOnly?>("From")
                        .HasColumnType("date")
                        .HasColumnName("from_date");

                    b.Property<DateTime?>("HeartbeatAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("heartbeat_at_utc");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mode");

                    b.Property<int>("PriceRowsAdded")
                        .HasColumnType("integer")
                        .HasColumnName("price_rows_added");

                    b.Property<int>("PriceRowsUpdated")
                        .HasColumnType("integer")
                        .HasColumnName("price_rows_updated");

                    b.Property<int>("ReportsFailed")
                        .HasColumnType("integer")
                        .HasColumnName("reports_failed");

                    b.Property<int>("ReportsFound")
                        .HasColumnType("integer")
                        .HasColumnName("reports_found");

                    b.Property<int>("ReportsImported")
                        .HasColumnType("integer")
                        .HasColumnName("reports_imported");

                    b.Property<int>("ReportsSkipped")
                        .HasColumnType("integer")
                        .HasColumnName("reports_skipped");

                    b.Property<string>("RequestJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("request_json");

                    b.Property<string>("ResultJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("result_json");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateOnly?>("To")
                        .HasColumnType("date")
                        .HasColumnName("to_date");

                    b.HasKey("Id");

                    b.HasIndex("ActiveSlot")
                        .IsUnique()
                        .HasFilter("active_slot IS NOT NULL");

                    b.HasIndex("Status", "CreatedAtUtc");

                    b.ToTable("doe_import_job", (string)null);
                });

            modelBuilder.Entity("DoePageCache", b =>
                {
                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<string>("ExtractorVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("extractor_version");

                    b.Property<int>("PageNumber")
                        .HasColumnType("integer")
                        .HasColumnName("page_number");

                    b.Property<DateTime>("ExtractedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("extracted_at_utc");

                    b.Property<string>("ExtractionJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("extraction_json");

                    b.Property<int>("PageCount")
                        .HasColumnType("integer")
                        .HasColumnName("page_count");

                    b.HasKey("ContentHash", "ExtractorVersion", "PageNumber");

                    b.ToTable("doe_page_cache", (string)null);
                });

            modelBuilder.Entity("DoePumpPriceReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at_utc");

                    b.Property<int>("PriceRows")
                        .HasColumnType("integer")
                        .HasColumnName("price_rows");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("section");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Subdivision")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("subdivision");

                    b.Property<DateOnly>("WeekEnd")
                        .HasColumnType("date")
                        .HasColumnName("week_end");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date")
                        .HasColumnName("week_start");

                    b.HasKey("Id");

                    b.HasIndex("SourceUrl", "WeekStart")
                        .IsUnique();

                    b.HasIndex("Section", "Subdivision", "WeekStart");

                    b.ToTable("doe_pump_price_report", (string)null);
                });

            modelBuilder.Entity("FuelAdjustment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("DieselChangePerLiter")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("diesel_change_per_liter");

                    b.Property<DateTime?>("EffectiveAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_at_utc");

                    b.Property<DateOnly>("EffectiveDatePhilippines")
                        .HasColumnType("date")
                        .HasColumnName("effective_date_philippines");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at_utc");

                    b.Property<decimal?>("GasolineChangePerLiter")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("gasoline_change_per_liter");

                    b.Property<decimal?>("KeroseneChangePerLiter")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("kerosene_change_per_liter");

                    b.Property<string>("OilCompany")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("oil_company");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source_url");

                    b.Property<DateOnly>("WeekEnd")
                        .HasColumnType("date")
                        .HasColumnName("week_end");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date")
                        .HasColumnName("week_start");

                    b.HasKey("Id");

                    b.HasIndex("WeekStart", "OilCompany", "EffectiveAtUtc")
                        .IsUnique()
                        .HasFilter("effective_at_utc IS NOT NULL");

                    b.HasIndex("WeekStart", "OilCompany", "EffectiveDatePhilippines")
                        .IsUnique()
                        .HasFilter("effective_at_utc IS NULL");

                    b.ToTable("fuel_adjustment", (string)null);
                });

            modelBuilder.Entity("FuelNews", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("category");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content_json");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("ImportKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("import_key");

                    b.Property<DateTime>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupersededById")
                        .HasColumnType("uuid")
                        .HasColumnName("superseded_by_id");

                    b.Property<string>("TopicKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("topic_key");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ImportKey")
                        .IsUnique();

                    b.HasIndex("SupersededById");

                    b.HasIndex("PublishedAtUtc", "Id");

                    b.HasIndex("TopicKey", "Status");

                    b.ToTable("fuel_news", (string)null);
                });

            modelBuilder.Entity("FuelNewsDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppInstanceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("app_instance_id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Error")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error");

                    b.Property<Guid>("NewsId")
                        .HasColumnType("uuid")
                        .HasColumnName("news_id");

                    b.Property<DateTime>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("TicketId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id");

                    b.HasIndex("AppInstanceId");

                    b.HasIndex("Status", "NextAttemptAtUtc");

                    b.HasIndex("NewsId", "Revision", "AppInstanceId")
                        .IsUnique();

                    b.ToTable("fuel_news_delivery", (string)null);
                });

            modelBuilder.Entity("FuelNewsRevision", b =>
                {
                    b.Property<Guid>("NewsId")
                        .HasColumnType("uuid")
                        .HasColumnName("news_id");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content_json");

                    b.Property<DateTime>("SavedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("saved_at_utc");

                    b.HasKey("NewsId", "Revision");

                    b.ToTable("fuel_news_revision", (string)null);
                });

            modelBuilder.Entity("FuelNewsSubscription", b =>
                {
                    b.Property<string>("AppInstanceId")
                        .HasColumnType("text")
                        .HasColumnName("app_instance_id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<bool>("IncludeForecasts")
                        .HasColumnType("boolean")
                        .HasColumnName("include_forecasts");

                    b.Property<string>("PushToken")
                        .IsRequired()
                        .HasMaxLength(230)
                        .HasColumnType("character varying(230)")
                        .HasColumnName("push_token");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("AppInstanceId");

                    b.HasIndex("PushToken")
                        .IsUnique();

                    b.ToTable("fuel_news_subscription", (string)null);
                });

            modelBuilder.Entity("FuelPriceCache", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cached_at");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("CityKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city_key");

                    b.Property<long>("HitCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("hit_count");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("province");

                    b.Property<string>("ProvinceKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("province_key");

                    b.Property<DateTime>("RefreshAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_after");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("region");

                    b.Property<string>("RegionKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("region_key");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("result_json");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("scope");

                    b.HasKey("Id");

                    b.HasIndex("Scope", "RegionKey", "CachedAt");

                    b.HasIndex("Scope", "ProvinceKey", "CityKey", "CachedAt");

                    b.ToTable("fuel_price_cache", (string)null);
                });

            modelBuilder.Entity("Guest", b =>
                {
                    b.Property<string>("AppInstanceId")
                        .HasColumnType("text")
                        .HasColumnName("app_instance_id");

                    b.Property<DateTime?>("AccessTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("access_token_expires_at");

                    b.Property<string>("AccessTokenHash")
                        .HasColumnType("text")
                        .HasColumnName("access_token_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceType")
                        .HasColumnType("text")
                        .HasColumnName("device_type");

                    b.Property<string>("GuestCredentialHash")
                        .HasColumnType("text")
                        .HasColumnName("guest_credential_hash");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsLoggedIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_logged_in");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("LastLogoutAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_logout_at");

                    b.Property<string>("LegacyToken")
                        .HasColumnType("text")
                        .HasColumnName("legacy_token");

                    b.Property<int>("LoginCount")
                        .HasColumnType("integer")
                        .HasColumnName("login_count");

                    b.Property<int>("LogoutCount")
                        .HasColumnType("integer")
                        .HasColumnName("logout_count");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("player_name");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.HasKey("AppInstanceId");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.HasIndex("PlayerName")
                        .IsUnique();

                    b.ToTable("guests", (string)null);
                });

            modelBuilder.Entity("PlayerData", b =>
                {
                    b.Property<string>("AppInstanceId")
                        .HasColumnType("text")
                        .HasColumnName("app_instance_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExtraDataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("extra_data_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<int>("Health")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100)
                        .HasColumnName("health");

                    b.Property<string>("InventoryJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("inventory_json")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<long>("Money")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("money");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<string>("PositionJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("position_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AppInstanceId");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("player_data", (string)null);
                });

            modelBuilder.Entity("DoeFuelPrice", b =>
                {
                    b.HasOne("DoePumpPriceReport", null)
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FuelNews", b =>
                {
                    b.HasOne("FuelNews", null)
                        .WithMany()
                        .HasForeignKey("SupersededById")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FuelNewsDelivery", b =>
                {
                    b.HasOne("FuelNewsSubscription", null)
                        .WithMany()
                        .HasForeignKey("AppInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuelNewsRevision", null)
                        .WithMany()
                        .HasForeignKey("NewsId", "Revision")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FuelNewsRevision", b =>
                {
                    b.HasOne("FuelNews", null)
                        .WithMany()
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FuelNewsSubscription", b =>
                {
                    b.HasOne("Guest", null)
                        .WithOne()
                        .HasForeignKey("FuelNewsSubscription", "AppInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlayerData", b =>
                {
                    b.HasOne("Guest", null)
                        .WithOne()
                        .HasForeignKey("PlayerData", "AppInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
