// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260914172237_AddFuelPriceCache")]
    partial class AddFuelPriceCache
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FuelPriceCache", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cached_at");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("CityKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city_key");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("province");

                    b.Property<string>("ProvinceKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("province_key");

                    b.Property<DateTime>("RefreshAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_after");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("result_json");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("scope");

                    b.HasKey("Id");

                    b.HasIndex("Scope", "ProvinceKey", "CityKey", "CachedAt");

                    b.ToTable("fuel_price_cache", (string)null);
                });

            modelBuilder.Entity("Guest", b =>
                {
                    b.Property<string>("AppInstanceId")
                        .HasColumnType("text")
                        .HasColumnName("app_instance_id");

                    b.Property<DateTime?>("AccessTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("access_token_expires_at");

                    b.Property<string>("AccessTokenHash")
                        .HasColumnType("text")
                        .HasColumnName("access_token_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceType")
                        .HasColumnType("text")
                        .HasColumnName("device_type");

                    b.Property<string>("GuestCredentialHash")
                        .HasColumnType("text")
                        .HasColumnName("guest_credential_hash");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsLoggedIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_logged_in");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("LastLogoutAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_logout_at");

                    b.Property<string>("LegacyToken")
                        .HasColumnType("text")
                        .HasColumnName("legacy_token");

                    b.Property<int>("LoginCount")
                        .HasColumnType("integer")
                        .HasColumnName("login_count");

                    b.Property<int>("LogoutCount")
                        .HasColumnType("integer")
                        .HasColumnName("logout_count");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("player_name");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.HasKey("AppInstanceId");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.HasIndex("PlayerName")
                        .IsUnique();

                    b.ToTable("guests", (string)null);
                });

            modelBuilder.Entity("PlayerData", b =>
                {
                    b.Property<string>("AppInstanceId")
                        .HasColumnType("text")
                        .HasColumnName("app_instance_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExtraDataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("extra_data_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<int>("Health")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100)
                        .HasColumnName("health");

                    b.Property<string>("InventoryJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("inventory_json")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<long>("Money")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("money");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<string>("PositionJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("position_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AppInstanceId");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("player_data", (string)null);
                });

            modelBuilder.Entity("PlayerData", b =>
                {
                    b.HasOne("Guest", null)
                        .WithOne()
                        .HasForeignKey("PlayerData", "AppInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
